name: cast
description: Dart package to discover and connect with Chromecast devices
version: 2.0.0
homepage: https://github.com/jonathantribouharet/flutter_cast

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  bonsoir: ^5.1.8
  flutter:
    sdk: flutter
  protobuf: ^3.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  pedantic: ^1.11.1
  protoc_plugin: ^21.1.2
